// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/marketing-os/AIAssistant.tsx": () => import("../components/mockups/marketing-os/AIAssistant.tsx"),
  "./components/mockups/marketing-os/Analytics.tsx": () => import("../components/mockups/marketing-os/Analytics.tsx"),
  "./components/mockups/marketing-os/CampaignDetail.tsx": () => import("../components/mockups/marketing-os/CampaignDetail.tsx"),
  "./components/mockups/marketing-os/Collaboration.tsx": () => import("../components/mockups/marketing-os/Collaboration.tsx"),
  "./components/mockups/marketing-os/Dashboard.tsx": () => import("../components/mockups/marketing-os/Dashboard.tsx"),
  "./components/mockups/marketing-os/TaskBoard.tsx": () => import("../components/mockups/marketing-os/TaskBoard.tsx")
};
